### ISSUE TITLE
How to keep connection alive?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#739] opened 2021-05-16 08:49 UTC
Hi,

I have socket subscriptions for spot and margin trades and anytime for example I buy or sell a new coin I add or remove it from my app gridview control's list so that for example when I wake up I can see I have coin X or Y and see their PNL.

But a lot of times the socket connection seems to be lost so that I don't get any of these updates. I have to restart the app and then my app will detect if any new coin is in my wallet but not on the logs.

JKorf said I have to use keepAlive function but I couldn't find this anywhere using the object browser.

Any help is appreciated!

`			var spotListenKey = client.Spot.UserStream.StartUserStreamAsync ( );
			var marginListenKey = client.Margin.UserStream.StartUserStreamAsync ( );

			// Subscribe to a user stream | SPOT account
			socketClient.Spot.SubscribeToUserDataUpdates ( spotListenKey.Result.Data,
				// Order update
				data =>
				{
					// Order update
					string symbol = Utility.GetBaseSymbol ( data.Symbol );
					if ( data.Side == OrderSide.Buy )
						Utility.UpdateActions.Enqueue ( new UpdateActionType ( UpdateType.BuyOrder, data ) );
					else if ( data.Side == OrderSide.Sell )
						Utility.UpdateActions.Enqueue ( new UpdateActionType ( UpdateType.SellOrder, data ) );
				},
				// OCO updates
				null,
				// Position updates
				null,
				// Balance updates
				data =>
				{
					Utility.UpdateActions.Enqueue ( new UpdateActionType ( UpdateType.BalanceUpdate, data ) );
				}
				);

			// Subscribe to a user stream | MARGIN account
			socketClient.Spot.SubscribeToUserDataUpdates ( marginListenKey.Result.Data,
				// Order update
				data =>
				{
					string symbol = Utility.GetBaseSymbol ( data.Symbol );
					if ( data.Side == OrderSide.Buy )
						Utility.UpdateActions.Enqueue ( new UpdateActionType ( UpdateType.BuyOrder, data ) );
					else if ( data.Side == OrderSide.Sell )
						Utility.UpdateActions.Enqueue ( new UpdateActionType ( UpdateType.SellOrder, data ) );
				},
				// OCO updates
				null,
				// Position updates
				null,
				// Balance updates
				data =>
				{
					Utility.UpdateActions.Enqueue ( new UpdateActionType ( UpdateType.BalanceUpdate, data ) );
				}
				);`

**Comment by ZigmundL** [comment] 2021-05-16 23:55
var reqResult = restClient.Spot.UserStream.KeepAliveUserStream(ListenKey);

**Comment by PDun** [comment] 2021-05-20 14:36
I had a similar issue and I think I had multiple connections to the same API and a new one will cause the old one to timeout IIRC. Has been a while.

**Comment by orionflame** [comment] 2021-05-31 01:34
For me everything works for some time but after some time it stops triggering actions for buy and sell orders on Spot and Margin accounts.

The prices still update, etc but the orders do not get received. I dont know why.

Even Binance's own desktop app stops working some features after a while no? So maybe this is inherent to the API?

**Comment by JKorf** [comment] 2021-05-31 09:54
I've seen the same issue. After some time the user stream doesn't seem to be sending updates anymore, even after sending a keep alive on the listenkey every 30 minutes as recommended. I've added a check in my project that when an order is placed but no update was received the order is retrieved via the rest client, and when this happens twice the socket is restarted. 
It's not ideal but it might be a work around for you.

I'm not sure what to do about the issue that Binance stops sending data. Seems to be an issue on the Binance side. The socket remains open, just doesn't receive any updates anymore.

**Comment by Sergey-A-Dvortsov** [comment] 2021-06-02 12:11
> I've seen the same issue. After some time the user stream doesn't seem to be sending updates anymore, even after sending a keep alive on the listenkey every 30 minutes as recommended. I've added a check in my project that when an order is placed but no update was received the order is retrieved via the rest client, and when this happens twice the socket is restarted.
> It's not ideal but it might be a work around for you.

Are you only restarting the socket? Does the rest client not restart and the old listenkey remains?

**Comment by orionflame** [comment] 2021-06-04 08:44
Thanks a lot JKorf for confirming. Because even Binance's own desktop app starts acting weird after some time. So they are definitely doing something wrong.

For some reason it seems worse in these months. Before I could receive updates quite a long time but now even after 30 mins things seems to go out of sync.

Is there any sample that shows the workaround you are using? I don't know how you check when an order is placed outside the SubscribeToUserDataUpdates functions. Is that what the rest client is for?

**Comment by JKorf** [comment] 2021-06-04 09:14
There is no build in way to detect this. I've solved it for my application by keeping track what orders are placed, and if no order update is received more than 10 seconds after the order was placed then close the subscription and resubscribe the user stream. 

It's not an ideal solution, still might miss order updates without knowing

@Sergey-A-Dvortsov I mean unsubscribing, creating a new listen key and resubscribing

**Comment by orionflame** [comment] 2021-06-04 09:17
Thanks @JKorf but how do you keep track of what orders are placed outside the above function I posted? I have a log file I keep the records but I dont know any way to verify if there is a new order that's supposed to be there.

Or are you saying you query past order every N interval?

**Comment by JKorf** [comment] 2021-06-04 09:20
You can keep an in-memory list when you place an order. When you call the PlaceOrder method, add an entry to your in-memory list with a timestamp. You could maybe keep track of whether or not it is confirmed by the socket client by adding some boolean to the object. Then have a task which checks every x seconds to see if there are any successfully placed orders which are not confirmed by the socket client and are placed more than x seconds ago.

**Comment by orionflame** [comment] 2021-06-04 09:24
Thanks @JKorf . Oh I see what you mean now. Because my application is only a monitor of my portfolio showing me unrealized PNL, etc, it doesn't place any orders, only I do it using the Binance app or desktop app. So I guess in my case there is no other way to verify unless I compare coin holdings, etc. I have a function to check all coins in my balance though it's a slow function.

**Comment by JKorf** [comment] 2021-06-04 09:45
Ah yes that is a different situation. It would be hard to detect in your case. You could also just resubscribe every hour or so, but there is still a chance you'd miss an update while resubscribing

**Comment by orionflame** [comment] 2021-06-04 11:48
Thanks a lot @JKorf . I will give it a try. At least I know it's not coz of my code nor your wrapper :)

**Comment by orionflame** [comment] 2021-06-08 03:53
Btw I saw today when I did some trades on binance app while having my app running (more than 1 day), i noticed it did pick up the orders. So that just shows it's binance screwing up. i didn't change anything in code.

**Comment by JKorf** [comment] 2021-06-08 06:33
It seems pretty stable for me as well at the moment. I'll close this issue as it doesn't seem to be related to the library.

**Closed by JKorf** 2021-06-08 06:33 UTC

**Comment by Smileynator** [comment] 2021-06-20 12:43
Sorry to necro this, but i saw in another part of the documentation the following:
https://binance-docs.github.io/apidocs/spot/en/#user-data-streams
`A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark`

Meaning that after 24 hours, you are most likely going to need a reconnect anyway? Your work around of 10 seconds no order update is what i am probably going to apply as well. But it is less than ideal that the connection just dies without warnings.
