### ISSUE TITLE
socket closed

### ISSUE THREAD

**Issue by darkness98** [JKorf/Binance.Net#47] opened 2018-03-04 01:47 UTC
Why after calling this function socked is closed ?  
```
var Openoderd = socketClient.SubscribeToUserStream(successStart.Data.ListenKey, (data) =>
                 {
                     
                     
                 },
                (orderInfoUpdate) =>
                {

                    
                   foreach (var ds in orderInfoUpdate.Symbol)
                        Console.WriteLine(ds);

                });
```
![img_04032018_044241_0](https://user-images.githubusercontent.com/1670619/36941190-97aa998c-1f66-11e8-989f-a48e6e6fcec6.png)

**Comment by darkness98** [comment] 2018-03-04 22:34
Maybe someone had the same problem?

**Comment by Swisization** [comment] 2018-03-04 23:54
I have a similar problem, stream does not work
Help please!
```
var Openoderd = socketClient.SubscribeToUserStream(successStart.Data.ListenKey,(data) =>
                {
                },
                  (orderInfoUpdate) =>
                  {
                      asd = orderInfoUpdate;
                  });
                System.Threading.Thread.Sleep(200000);
                    Console.WriteLine(asd.Time);
```
![image](https://user-images.githubusercontent.com/36995625/36952399-79a9ded8-2020-11e8-976c-b5e6f347d5b5.png)

**Comment by JKorf** [comment] 2018-03-05 13:48
Hi, I think the problem is that your socketClient gets disposed, which means it will close the connections.
Make sure the socketClient is saved somewhere outside of the function where you use it, not just a local variable.

**Comment by Swisization** [comment] 2018-03-05 14:11
I did the same as in the example github.com/JKorf/Binance.Net/blob/master/Examples/ClientConsole/Program.cs
ListenKey is transferred, but does not work for some reason, or is it an obsolete example?

**Comment by JKorf** [comment] 2018-03-05 14:16
The example is a bit out of date, I'm in the process of updating it. It might be a bit misleading since it uses the BinanceSocketClient in a using(){} statement, but it will be disposed after leaving that.
So instead of
````C#
using(var socketClient = new BinanceSocketClient())
{
    // subscribe and stuff
}
````
you probably want to do this
````C#
class SomeClass
{
    BinanceSocketClient socketClient;
    public SomeClass()
    {
        socketClient = new BinanceSocketClient();
    }

    public void Start(string listenKey)
    {
        // subscribe and stuff
    }
}
````

**Comment by Swisization** [comment] 2018-03-06 14:03
I did this as in the new example, and this function returns null value again (other functions work fine)
![image](https://user-images.githubusercontent.com/36995625/37036233-0c1270e2-2160-11e8-9061-cb1c5e88a24c.png)
![image](https://user-images.githubusercontent.com/36995625/37036249-1c5b38e4-2160-11e8-86ce-73f345b16325.png)

**Comment by JKorf** [comment] 2018-03-06 15:18
You're waiting 10 seconds for the event to occur, but the event will only happen if something changes in your account/balances. Also this is probably not how you want to handle the data. Consider something like this:
````C#
class Program
    {
        static void Main(string[] args)
        {
            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials("APIKEY", "APISECRET")
            });

            string listenKey;
            using (var client = new BinanceClient())
                listenKey = client.StartUserStream().Data.ListenKey;

            var socketClient = new BinanceSocketClient();
            socketClient.SubscribeToUserStream(listenKey, AccountInfoUpdate, OrderUpdateInfo);
            Console.ReadLine();
        }

        private static void AccountInfoUpdate(BinanceStreamAccountInfo info)
        {
            foreach(var balance in info.Balances)
                Console.WriteLine(balance.Asset + ": " + balance.Total);
        }

        private static void OrderUpdateInfo(BinanceStreamOrderUpdate info)
        {
            // order update
        }
    }
````
If you run this and you log in to the Binance website and place an order it will write your updated balances to the screen. 

The Subscribe methods in the socket client aren't just functions that will get a value, they will trigger whenever something happens, and you probably shouldn't use them to just 1 time get a value. To do that you should use the BinanceClient:
````C#
using(var client = new BinanceClient())
{
    var accountInfoResult = client.GetAccountInfo();
}
````

**Comment by Swisization** [comment] 2018-03-06 17:35
thank you very much for the help

**Comment by JKorf** [comment] 2018-03-07 07:38
@darkness98 have you managed to get it working as well?

**Comment by darkness98** [comment] 2018-03-12 20:46
@JKorf Yes, thank you

**Closed** 2018-03-12 20:46 UTC
