### ISSUE TITLE
Error 5 : GetOpenOrders()

### ISSUE THREAD

**Issue by Sergey7733** [JKorf/Binance.Net#313] opened 2020-05-03 08:41 UTC
![Error 5](https://user-images.githubusercontent.com/50843886/80909701-ed757300-8d32-11ea-9d01-d9944f5440f1.JPG)

**Comment by JKorf** [comment] 2020-05-08 06:44
Hi, I can't reproduce this, is this a consistent error for you? Can you share the data which was returned?

**Comment by Hulkstance** [comment] 2020-05-14 05:29
> 
> 
> ![Error 5](https://user-images.githubusercontent.com/50843886/80909701-ed757300-8d32-11ea-9d01-d9944f5440f1.JPG)

That's because you didn't update the nuget package.

![image](https://user-images.githubusercontent.com/33224919/81896312-085ea780-95bd-11ea-90d0-7603ca557e21.png)

**Comment by Sergey7733** [comment] 2020-05-21 19:08
did you receive my email with data? to: jankorf91@gmail.com
--

**Comment by JKorf** [comment] 2020-06-03 12:02
@Sergey7733 The code you sent me works for me. Can you try again with the latest version? Your problem might be fixed by a recent release.

**Closed** 2020-06-26 07:29 UTC
