### ISSUE TITLE
Client.PlaceTestOrder

### ISSUE THREAD

**Issue by tuxkilla** [JKorf/Binance.Net#5] opened 2017-12-26 14:20 UTC
It seems as though the API is mandating a TimeInForce parameter to be sent into the Client.PlaceTestOrder function even when the OrderType.Market enum is used. This is causing the Binance API to send back the error message below:

Code = -1106
Message = "Parameter 'timeInForce' sent when not required."

If you use OrderType.Limit, this issue does not occur.
Thanks!

**Comment by romanukanton** [comment] 2018-01-06 11:59
I have the same problem. Also I don't understand why we need to enter price for "market order".

**Comment by JKorf** [comment] 2018-01-08 13:40
Hi, I've adjusted the required parameters is the latest version, this should fix your problems!

**Comment by romanukanton** [comment] 2018-01-11 07:04
Hi, thanks, it works perfect. But I have another problem. When I receive message   from "SubscribeToOrderUpdateStream" application falls down. What am I doing wrong? here is part of my code
` public BinanceClient client = new BinanceClient("LtayOe3zt0r2woOOyiqaV294ur0UpAs81bYXFbSjPEOnGjFsOrlKl9qwBAJxWWFf", "l7981P2MAk3xZ5pXueZm9F8q60KVSD3k4oGkfr6PK9wFo4c2dDeEYMhKXGK2zJpK");
        public BinanceSocketClient bsc = new BinanceSocketClient();
        private async void button1_Click(object sender, EventArgs e)
        {
            var lkey = await  client.StartUserStreamAsync();
            bsc.SubscribeToOrderUpdateStream(lkey.Data.ListenKey, onMyOrderUpdate);
            var tt= await client.KeepAliveUserStreamAsync(lkey.Data.ListenKey);
            if (tt.Success)
            {
                MessageBox.Show("Keep Alive Success");
            }
        }
        private void onMyOrderUpdate(BinanceStreamOrderUpdate data)
        {
            MessageBox.Show(data.Price.ToString());
        }`

**Comment by BenVlodgi** [comment] 2018-01-11 18:00
@romanukanton update your comment to not have your APIKey and APISecret. Then go deactivate that APIKey and APISecret. And generate a new one.

**Comment by romanukanton** [comment] 2018-01-11 20:55
Done

**Comment by JKorf** [comment] 2018-01-12 08:56
I think that is a duplicate of #7? If not, please make a new issue describing what the problem is.

**Closed by JKorf** 2018-01-12 08:56 UTC

**Comment by aks3213** [comment] 2021-03-11 05:27
can any one post code or project with basic functions used in it.
Because it seems difficult to me while passing parameters to functions.

**Comment by aks3213** [comment] 2021-03-11 05:40
```
var temp = await client.Spot.Order.PlaceTestOrderAsync(symbol, Binance.Net.Enums.OrderSide.Buy, Binance.Net.Enums.OrderType.Limit, 1, null, null, 1, Binance.Net.Enums.TimeInForce.GoodTillCancel, null, null, Binance.Net.Enums.OrderResponseType.Acknowledge, null, default);
                var jsonObj = Newtonsoft.Json.JsonConvert.SerializeObject(temp);

                return View(jsonObj);

```
![Untitled](https://user-images.githubusercontent.com/68645565/110740934-d8724600-8259-11eb-8eea-523b4c90b6b1.png)

![Uploading Untitled1.png…]()
