### ISSUE TITLE
GetExchangeInfoAsync().Result.Data return null

### ISSUE THREAD

**Issue by icewind-i7** [JKorf/Binance.Net#1012] opened 2022-02-26 15:35 UTC
Hello!

GetExchangeInfoAsync().Result.Data return null but a few days ago it worked.
GetExchangeInfoAsync().Result.Success == false state.

All another functions is working.
I try version 8.0.3 but is not help.

Best regards!

**Comment by M22arius494** [comment] 2022-02-28 08:40
I have the same problem, but its kind of intermitting. Could be Binance itself, but since it worked previously in #7 i guess its the library.

**Comment by salmasi** [comment] 2022-02-28 20:55
Full error in v8.0.4

> Deserialize Unknown Exception: IOException - Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.FillBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 numBytesRequired)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.Read(Span`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
   at System.IO.StreamReader.ReadSpan(Span`1 buffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at CryptoExchange.Net.BaseClient.DeserializeAsync[T](Stream stream, JsonSerializer serializer, Nullable`1 requestId, Nullable`1 elapsedMilliseconds)
  SocketException - An existing connection was forcibly closed by the remote host.

**Comment by salmasi** [comment] 2022-03-01 08:26
i think this is very critical bug in the latest version because GetExchangeInfo is very useful function
@JKorf

**Comment by salmasi** [comment] 2022-03-01 18:39
THANKS @JKorf 
i update to 8.0.5 and error gone 👍

**Comment by M22arius494** [comment] 2022-03-02 17:37
> I'm not able to reproduce this. There was an issue in deserialization which was fixed in 8.0.3, but this doesn't seem related. From the stacktrace you posted @salmasi it seems like the connection is closed before the full response has been received. @icewind-i7, @M22arius494 Can you confirm this is the same error you're seeing?
> 
> I this is the case I don't think it's related to the latest version, but I'll see if I can find anything

No sorry, I have been deleting all my nlog files and cannot reproduce this error at this moment. I would sugges closing as you suggested

**Closed** 2022-03-08 09:15 UTC
