### ISSUE TITLE
"Not authorized" when transfering from Futures to Spot

### ISSUE THREAD

**Issue by Jenscaasen** [JKorf/Binance.Net#733] opened 2021-05-11 11:33 UTC
Hi,
i am not entirely sure this is an issue with the lib, it could also be an API Key issue **if** you need "withdrawal" rights for the key to do transfers (do you?). Anyway:

`var transferResult =     client.Spot.Futures.TransferFuturesAccount(transferType: FuturesTransferType.FromUsdtFuturesToSpot, asset: "USDT", amount: 10);`
This results in ""You are not authorized to execute this request."

The guess, why this might be an issue with the Lib is this: https://dev.binance.vision/t/isolated-margin-order-api-not-authorized/675

Similar situation, solution is described as:

> "In Python requests the request body needs to be sent as “params” not as “data”.
> It works as “data” at spot trading but not at margin trading."

Does this lib maybe also use "data" instead of "params" in terms of futures?

**Comment by HypsyNZ** [comment] 2021-05-18 02:42
> it could also be an API Key issue if you need "withdrawal" rights for the key to do transfers (do you?). 

It seems so, Yes.

**Comment by JKorf** [comment] 2021-05-31 10:55
Just enable Withdraw permission and see if it works ;)

**Comment by JKorf** [comment] 2021-05-31 11:02
Also; duplicate of #730

**Closed by JKorf** 2021-05-31 11:02 UTC
