### ISSUE TITLE
FuturesUsdt.System.GetExchangeInfo() Ver6.5 Error

### ISSUE THREAD

**Issue by zlingqing** [JKorf/Binance.Net#531] opened 2021-01-05 07:42 UTC
V6.4.0.0正常，更新V6.5之后报错，是否版本问题？
错误如下：
{: [1] Deserialize JsonSerializationException: Error setting value to 'ContractType' on 'Binance.Net.Objects.Futures.MarketData.BinanceFuturesUsdtSymbol'.
[GetExchangeInfo_Error.txt](https://github.com/JKorf/Binance.Net/files/5768718/GetExchangeInfo_Error.txt)

**Comment by JKorf** [comment] 2021-01-05 08:10
Duplicate of #530

**Closed by JKorf** 2021-01-05 08:10 UTC
